//! `sw-cdp1802-isa`: RCA CDP1802 ISA description: opcodes, encoding, decoding, disassembly.
//!
//! Skeleton generated by `gen-isa`. Hand-fill the per-ISA logic
//! against the trait surfaces in `sw-langtools`.

pub mod opcode;
pub mod register;
pub mod encode;
pub mod decode;
pub mod branch;

/// Marker type that will implement `sw_isa_core::Architecture`.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct Cdp1802;
